### ISSUE TITLE
Suggestion for the docs: slug risk

### ISSUE THREAD

**Issue by evertalbers** [PhillippOhlandt/bolt-extension-required-records#1]
The slug (and possibly some other fields, too?) by default add something to the name, e.g. (in case of a slug for a page) "page-1". 
If a number of items has been defined with a required slug name his creates the risk of users hitting Extras => Required Records several times and thus creating many obsolete items - which then have to be cleaned up.

I'm not sure if this can be solved within your extension, but you might want to add a warning about this in the docs.

**Comment by PhillippOhlandt** [comment]
Solved in Slack.
